apiVersion: apps/v1
kind: Deployment
metadata:
  name: k8s-rollout-test-2
spec:
  selector:
    matchLabels:
      app: k8s-rollout-test-2
  replicas: 2
  template:
    metadata:
      labels:
        app: k8s-rollout-test-2
    spec:
      # This parameter ensures that the node will not shut down while it 
      # still has running connections to handle.
      terminationGracePeriodSeconds: 5
      containers:
        - name: k8s-rollout-test-2
          image: "k8s-rollout-test:0.0.1"
          ports:
            - containerPort: 8080
          readinessProbe:
            httpGet:
              path: /
              port: 8080
            initialDelaySeconds: 1
            periodSeconds: 1
            timeoutSeconds: 2
            successThreshold: 1
            failureThreshold: 3
          livenessProbe:
            httpGet:
              path: /
              port: 8080
            initialDelaySeconds: 1
            periodSeconds: 1
            timeoutSeconds: 1
            successThreshold: 1
            failureThreshold: 3
          # This gives ability to handle in-flight requests in parallel with 
          # SIGTERM call
          lifecycle:
            preStop:
              exec:
                command: ["sh", "-c", "sleep 5"]
          env:
            - name: RANDOM
              value: "2"
---
kind: Service
apiVersion: v1
metadata:
  name: k8s-rollout-test-2
spec:
  type: NodePort
  selector:
    app: k8s-rollout-test-2
  ports:
    - port: 8080
      targetPort: 8080
      nodePort: 30466