apiVersion: apps/v1
kind: Deployment
metadata:
  name: k8s-rollout-test
spec:
  selector:
    matchLabels:
      app: k8s-rollout-test
  replicas: 2
  template:
    metadata:
      labels:
        app: k8s-rollout-test
    spec:
      # This parameter ensures that the node will not shut down while it 
      # still has running connections to handle.
      containers:
        - name: k8s-rollout-test
          image: "k8s-rollout-test:0.0.1"
          ports:
            - containerPort: 8080
          readinessProbe:
            httpGet:
              path: /
              port: 8080
            initialDelaySeconds: 1
            periodSeconds: 1
            timeoutSeconds: 2
            successThreshold: 1
            failureThreshold: 3
          livenessProbe:
            httpGet:
              path: /
              port: 8080
            initialDelaySeconds: 1
            periodSeconds: 1
            timeoutSeconds: 1
            successThreshold: 1
            failureThreshold: 3
          env:
            - name: RANDOM
              value: "1"
---
kind: Service
apiVersion: v1
metadata:
  name: k8s-rollout-test
spec:
  type: NodePort
  selector:
    app: k8s-rollout-test
  ports:
    - port: 8080
      targetPort: 8080
      nodePort: 30466